# Generated by Django 3.2.5 on 2021-08-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210731_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='applicant_image',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='hospital_image',
        ),
    ]
