# Generated by Django 3.2.5 on 2021-08-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210801_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='applicant_address',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='applicant_address2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='applicant_pincode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_address',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
