# Generated by Django 3.2.5 on 2021-08-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_hospital_applicant_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_image',
            field=models.ImageField(default=0, upload_to='image'),
            preserve_default=False,
        ),
    ]
