# Generated by Django 3.2.5 on 2021-08-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_hospital_hospital_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
