export const HOSPITAL_REGISTER_REQUEST = 'HOSPITAL_REGISTER_REQUEST'
export const HOSPITAL_REGISTER_SUCCESS = 'HOSPITAL_REGISTER_SUCCESS'
export const HOSPITAL_REGISTER_FAIL = 'HOSPITAL_REGISTER_FAIL'
